# Using default settings and adding our own overrides
use_default_settings: true

server:
  # This secret_key is just a placeholder.
  # Koyeb's environment variable will override it.
  secret_key: ${SECRET_KEY}
  limiter: false

image_proxy: true

search:
  # options available for formats: [html, csv, json, rss]
  formats:
    - html
    - json
